name: Snapshot to OCI
on:
  push:
    branches:
      - oci-deploy 
jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Run Tests
        run: ./gradlew starter-api:test starter-web-netty:test starter-gcp-function:shadowJar
      - name: Build Docker image
        run: |
          docker build . --tag iad.ocir.io/${{ secrets.OCI_REPO }}/${{ secrets.OCI_SNAPSHOT_APP_NAME }}:snapshot -f DockerfileCloudRun
      - name: Docker login
        run: |
          docker login --username ${{ secrets.OCIR_USERNAME }} --password ${{ secrets.OCIR_TOKEN }} iad.ocir.io
      
      - name: Push image to Google Cloud Container Registry
        run: docker push iad.ocir.io/${{ secrets.OCI_REPO }}/${{ secrets.OCI_SNAPSHOT_APP_NAME }}:snapshot
     